import { Link } from 'react-router-dom'
import { PageLayout } from '@workspace/react-layout'

export default function AboutPage(): JSX.Element {
  return (
    <PageLayout className="prose">
      <h1>About</h1>
      <p>
        This project workspace template was created by <Link to="https://firxworx.com/">@firxworx</Link> (
        <Link to="https://github.com/firxworx">GitHub</Link>).
      </p>
      <p>
        It features <Link to="https://ui.shadcn.com/docs">shadcn/ui</Link>,{' '}
        <Link to="https://www.radix-ui.com/">radix-ui</Link>,{' '}
        <Link to="https://tailwindcss.com/docs/installation">tailwindcss</Link>, and the{' '}
        <Link to="https://fluid.tw/">fluid-tailwind plugin</Link> showcased in an example{' '}
        <Link to="https://react.dev/">react</Link> application with{' '}
        <Link to="https://reactrouter.com/en/main">react-router</Link>.
      </p>
      <p>
        Authored in <Link to="https://www.typescriptlang.org/">TypeScript</Link> and powered by{' '}
        <Link to="https://vite.dev/">Vite</Link>.
      </p>
      <p>
        The code is organized in a <Link to="https://pnpm.io/workspaces">pnpm workspace</Link> (monorepo) with react
        components, schemas & types (with <Link to="https://zod.dev/">zod</Link>), and{' '}
        <Link to="https://tailwindcss.com/docs/presets">tailwind presets</Link> shared as internal packages (libraries)
        that can be imported by multiple projects in the workspace.
      </p>
      <p>
        Linting and formatting by <Link to="https://biomejs.dev/">biome</Link>.
      </p>
      <p>
        A preview is deployed on <Link to="https://developers.cloudflare.com/pages/">Cloudflare Pages</Link>:
      </p>
      <div className="~p-4/6 rounded-md bg-muted/75 max-w-fit">
        <Link to="https://vite-shadcn-workspace.pages.dev">https://vite-shadcn-workspace.pages.dev</Link>
      </div>
      <h2>Acknowledgements</h2>
      <h3>Design</h3>
      <p>
        The landing page design and components are roughly based on the boilerplate code generated by the{' '}
        <Link to="https://kirimase.dev/">Kirimase CLI</Link> created by{' '}
        <Link to="https://www.nicoalbanese.com/">Nico Albanese</Link>.
      </p>
      <h3>Illustrations</h3>
      <p>
        The vector illustrations on the landing page are thanks to <Link to="https://popsy.co/">popsy.co</Link>.
      </p>
      <h3>Icons</h3>
      <p>
        Icons from <Link to="https://lucide.dev/">Lucide</Link> are distributed under its{' '}
        <Link to="https://lucide.dev/license">ISC License</Link>.
      </p>
      <p>
        The ownership of trademarks related to brands such as the GitHub logo or leading social media platforms belongs
        to their respective copyright holders. Icons related to these brands are distributed under fair-use.
      </p>

      <h2>License</h2>
      <p>
        Code is licensed under MIT by <Link to="https://firxworx.com/">Kevin Firko</Link> &{' '}
        <Link to="https://bitcurve.com/">Bitcurve</Link>.
      </p>
    </PageLayout>
  )
}
